apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: devportal
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'devteam1'
        static_configs:
          - targets: ['devteam1:8080']
        metrics_path: '/metrics'

      - job_name: 'devteam2'
        static_configs:
          - targets: ['devteam2:8080']
        metrics_path: '/metrics'

      - job_name: 'devteam3'
        static_configs:
          - targets: ['devteam3:8080']
        metrics_path: '/metrics'

      - job_name: 'devteam4'
        static_configs:
          - targets: ['devteam4:8080']
        metrics_path: '/metrics'

      - job_name: 'devteam5'
        static_configs:
          - targets: ['devteam5:8080']
        metrics_path: '/metrics'