name: devportal CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: nidarow/devportal-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-test-scan-push:
    name: Build, Test, Scan and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Restore App
        run: dotnet restore ./src/DevPortal.App/DevPortal.App.csproj

      - name: Restore Tests
        run: dotnet restore ./src/DevPortal.HealthCheck.Tests/DevPortal.HealthCheck.Tests.csproj

      - name: Build
        run: dotnet build ./src/DevPortal.App/DevPortal.App.csproj --no-restore -c Release

      - name: Test
        run: dotnet test ./src/DevPortal.HealthCheck.Tests/DevPortal.HealthCheck.Tests.csproj --no-restore -c Release

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -f src/DevPortal.App/Dockerfile -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -t ${{ env.IMAGE_NAME }}:latest .

      - name: Security scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: '1'
          severity: CRITICAL

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_NAME }}:latest